import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  // Embed web-dist files so BRAT installs work (BRAT only downloads main.js/manifest.json/styles.css)
  const fs = await import("fs");
  const appJs = fs.readFileSync("web-dist/app.js", "utf8");
  const indexHtml = fs.readFileSync("web-dist/index.html", "utf8");
  fs.appendFileSync("main.js", `\n//@ts-nocheck\nconst __EMBEDDED_WEB={"/index.html":${JSON.stringify(indexHtml)},"/app.js":${JSON.stringify(appJs)}};\n`);
  process.exit(0);
} else {
  await context.watch();
}
