/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GitbookPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var http = __toESM(require("http"));
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var DEFAULT_SETTINGS = {
  port: 3e3,
  siteTitle: "Vault Book"
};
function slugify(s) {
  return s.toLowerCase().replace(/[^\w]+/g, "-").replace(/^-+|-+$/g, "") || "untitled";
}
var MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon"
};
var GitbookPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.server = null;
    this.pluginDir = "";
  }
  async onload() {
    await this.loadSettings();
    const adapter = this.app.vault.adapter;
    const vaultPath = adapter.getBasePath();
    this.pluginDir = path.join(vaultPath, this.app.vault.configDir, "plugins", "obs-book");
    this.addCommand({
      id: "start-server",
      name: "Start Gitbook Server",
      callback: () => this.startServer()
    });
    this.addCommand({
      id: "stop-server",
      name: "Stop Gitbook Server",
      callback: () => this.stopServer()
    });
    this.addSettingTab(new GitbookSettingTab(this.app, this));
  }
  onunload() {
    this.stopServer();
  }
  async loadSettings() {
    this.settings = { ...DEFAULT_SETTINGS, ...await this.loadData() };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  stopServer() {
    if (this.server) {
      this.server.close();
      this.server = null;
    }
  }
  startServer() {
    this.stopServer();
    const vault = this.app.vault;
    const distDir = path.join(this.pluginDir, "web-dist");
    const getPages = () => {
      return vault.getMarkdownFiles().map((f) => ({
        slug: slugify(f.basename),
        title: f.basename,
        path: f.path
      })).sort((a, b) => a.title.localeCompare(b.title));
    };
    const serveStatic = (filePath, res) => {
      try {
        const data = fs.readFileSync(filePath);
        const ext = path.extname(filePath).toLowerCase();
        res.writeHead(200, { "Content-Type": MIME[ext] || "application/octet-stream" });
        res.end(data);
      } catch (e) {
        return false;
      }
      return true;
    };
    this.server = http.createServer(async (req, res) => {
      var _a;
      const url = new URL((_a = req.url) != null ? _a : "/", `http://localhost:${this.settings.port}`);
      const pname = url.pathname;
      res.setHeader("Access-Control-Allow-Origin", "*");
      res.setHeader("Access-Control-Allow-Headers", "Content-Type");
      if (pname === "/debug") {
        const exists = (p) => {
          try {
            fs.accessSync(p);
            return "\u2713";
          } catch (e) {
            return "\u2717";
          }
        };
        res.writeHead(200, { "Content-Type": "text/plain" });
        res.end(`pluginDir: ${this.pluginDir} (${exists(this.pluginDir)})
distDir: ${distDir} (${exists(distDir)})
index.html: (${exists(path.join(distDir, "index.html"))})
app.js: (${exists(path.join(distDir, "app.js"))})
`);
        return;
      }
      try {
        if (pname === "/api/settings") {
          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ siteTitle: this.settings.siteTitle }));
          return;
        }
        if (pname === "/api/pages") {
          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify(getPages()));
          return;
        }
        const pageMatch = pname.match(/^\/api\/page\/(.+)$/);
        if (pageMatch) {
          const slug = pageMatch[1];
          const pages = getPages();
          const page = pages.find((p) => p.slug === slug);
          if (!page) {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Not found" }));
            return;
          }
          const file = vault.getMarkdownFiles().find((f) => f.path === page.path);
          if (!file) {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Not found" }));
            return;
          }
          const content = await vault.read(file);
          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ slug, title: page.title, content }));
          return;
        }
        const staticPath = pname === "/" ? "/index.html" : pname;
        const filePath = path.join(distDir, staticPath.replace(/^\//, ""));
        if (serveStatic(filePath, res))
          return;
        const indexPath = path.join(distDir, "index.html");
        if (serveStatic(indexPath, res))
          return;
        res.writeHead(404);
        res.end("Not found");
      } catch (e) {
        res.writeHead(500);
        res.end("Server error");
      }
    });
    this.server.on("error", (err) => {
      if (err.code === "EADDRINUSE") {
        new import_obsidian.Notice(`Port ${this.settings.port} is in use. Try a different port.`);
      }
    });
    this.server.listen(this.settings.port, () => {
      new import_obsidian.Notice(`\u{1F4D6} Gitbook running at http://localhost:${this.settings.port}`);
    });
  }
};
var GitbookSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Port").setDesc("Web server port").addText(
      (text) => text.setValue(String(this.plugin.settings.port)).onChange(async (v) => {
        this.plugin.settings.port = parseInt(v) || 3e3;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Site title").setDesc("Title shown in sidebar").addText(
      (text) => text.setPlaceholder("My Gitbook").setValue(this.plugin.settings.siteTitle).onChange(async (v) => {
        this.plugin.settings.siteTitle = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Server").addButton(
      (btn) => btn.setIcon("play").setTooltip("Start").onClick(() => this.plugin.startServer())
    ).addButton(
      (btn) => btn.setIcon("x").setTooltip("Stop").onClick(() => this.plugin.stopServer())
    );
  }
};
